-- Inner Join
SELECT cli.ID, cli.NOME, vend.valor FROM CLIENTE cli 
INNER JOIN venda vend ON vend.ID_CLIENTE = cli.ID;

USE SAKILA;

-- Países de cada cidade cadastrada
SELECT CITY.CITY, COUNTRY.COUNTRY FROM CITY INNER JOIN
COUNTRY ON CITY.CITY_ID = COUNTRY.COUNTRY_ID;

-- Cidade cadastradas no Brasil e Argentina
SELECT CITY.CITY, COUNTRY.COUNTRY FROM CITY INNER JOIN
COUNTRY ON CITY.COUNTRY_ID = COUNTRY.COUNTRY_ID
WHERE COUNTRY.COUNTRY = 'BRAZIL' OR COUNTRY.COUNTRY = 'ARGENTINA';

-- ID de cada um dos filmes que os atores trabalharam
SELECT ACTOR.FIRST_NAME, ACTOR.LAST_NAME, FILM_ACTOR.FILM_ID 
FROM ACTOR INNER JOIN FILM_ACTOR ON ACTOR.ACTOR_ID = FILM_ACTOR.ACTOR_ID;

-- Filmes que John Suvari participou
SELECT ACTOR.FIRST_NAME, ACTOR.LAST_NAME, FILM_ACTOR.FILM_ID, FILM.TITLE 
FROM ACTOR INNER JOIN FILM_ACTOR ON ACTOR.ACTOR_ID = FILM_ACTOR.ACTOR_ID
INNER JOIN FILM ON FILM_ACTOR.FILM_ID = FILM.FILM_ID
WHERE ACTOR.FIRST_NAME = 'JOHN' AND ACTOR.LAST_NAME = 'SUVARI';

-- Título e idioma de todos os títulos cadastrados
SELECT FILM.TITLE, LANGUAGE.NAME FROM FILM
INNER JOIN LANGUAGE ON LANGUAGE.LANGUAGE_ID = FILM.LANGUAGE_ID; 